#!/bin/sh
# prerm script for php5-phalcon
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
	php5dismod phalcon
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
